/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AraRouteImport } from './routes/ara'
import { Route as GizlilikPolitikasiRouteImport } from './routes/gizlilik-politikasi'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as SartlarVeKosullarRouteImport } from './routes/sartlar-ve-kosullar'
import { Route as SeninHayatinNasilDegisirdiRouteImport } from './routes/senin-hayatin-nasil-degisirdi'
import { Route as YaPodcastRouteImport } from './routes/ya-podcast'
import { Route as YazarOlRouteImport } from './routes/yazar-ol'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminYeniYaziRouteImport } from './routes/admin/yeni-yazi'
import { Route as AuthorSlugRouteImport } from './routes/author/$slug'
import { Route as KategoriSlugRouteImport } from './routes/kategori/$slug'
import { Route as PagePageRouteImport } from './routes/page/$page'
import { Route as AdminDuzenleIdRouteImport } from './routes/admin/duzenle/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AraRoute = AraRouteImport.update({
  id: '/ara',
  path: '/ara',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikPolitikasiRoute = GizlilikPolitikasiRouteImport.update({
  id: '/gizlilik-politikasi',
  path: '/gizlilik-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const SartlarVeKosullarRoute = SartlarVeKosullarRouteImport.update({
  id: '/sartlar-ve-kosullar',
  path: '/sartlar-ve-kosullar',
  getParentRoute: () => rootRouteImport,
} as any)
const SeninHayatinNasilDegisirdiRoute =
  SeninHayatinNasilDegisirdiRouteImport.update({
    id: '/senin-hayatin-nasil-degisirdi',
    path: '/senin-hayatin-nasil-degisirdi',
    getParentRoute: () => rootRouteImport,
  } as any)
const YaPodcastRoute = YaPodcastRouteImport.update({
  id: '/ya-podcast',
  path: '/ya-podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const YazarOlRoute = YazarOlRouteImport.update({
  id: '/yazar-ol',
  path: '/yazar-ol',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminYeniYaziRoute = AdminYeniYaziRouteImport.update({
  id: '/admin/yeni-yazi',
  path: '/admin/yeni-yazi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorSlugRoute = AuthorSlugRouteImport.update({
  id: '/author/$slug',
  path: '/author/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagePageRoute = PagePageRouteImport.update({
  id: '/page/$page',
  path: '/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDuzenleIdRoute = AdminDuzenleIdRouteImport.update({
  id: '/admin/duzenle/$id',
  path: '/admin/duzenle/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/ara': typeof AraRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/sartlar-ve-kosullar': typeof SartlarVeKosullarRoute
  '/senin-hayatin-nasil-degisirdi': typeof SeninHayatinNasilDegisirdiRoute
  '/ya-podcast': typeof YaPodcastRoute
  '/yazar-ol': typeof YazarOlRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/yeni-yazi': typeof AdminYeniYaziRoute
  '/author/$slug': typeof AuthorSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/page/$page': typeof PagePageRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/duzenle/$id': typeof AdminDuzenleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/ara': typeof AraRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/sartlar-ve-kosullar': typeof SartlarVeKosullarRoute
  '/senin-hayatin-nasil-degisirdi': typeof SeninHayatinNasilDegisirdiRoute
  '/ya-podcast': typeof YaPodcastRoute
  '/yazar-ol': typeof YazarOlRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/yeni-yazi': typeof AdminYeniYaziRoute
  '/author/$slug': typeof AuthorSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/page/$page': typeof PagePageRoute
  '/admin': typeof AdminIndexRoute
  '/admin/duzenle/$id': typeof AdminDuzenleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/ara': typeof AraRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/sartlar-ve-kosullar': typeof SartlarVeKosullarRoute
  '/senin-hayatin-nasil-degisirdi': typeof SeninHayatinNasilDegisirdiRoute
  '/ya-podcast': typeof YaPodcastRoute
  '/yazar-ol': typeof YazarOlRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/yeni-yazi': typeof AdminYeniYaziRoute
  '/author/$slug': typeof AuthorSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/page/$page': typeof PagePageRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/duzenle/$id': typeof AdminDuzenleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/ara'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/iletisim'
    | '/sartlar-ve-kosullar'
    | '/senin-hayatin-nasil-degisirdi'
    | '/ya-podcast'
    | '/yazar-ol'
    | '/admin/login'
    | '/admin/yeni-yazi'
    | '/author/$slug'
    | '/kategori/$slug'
    | '/page/$page'
    | '/admin/'
    | '/admin/duzenle/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/ara'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/iletisim'
    | '/sartlar-ve-kosullar'
    | '/senin-hayatin-nasil-degisirdi'
    | '/ya-podcast'
    | '/yazar-ol'
    | '/admin/login'
    | '/admin/yeni-yazi'
    | '/author/$slug'
    | '/kategori/$slug'
    | '/page/$page'
    | '/admin'
    | '/admin/duzenle/$id'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/ara'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/iletisim'
    | '/sartlar-ve-kosullar'
    | '/senin-hayatin-nasil-degisirdi'
    | '/ya-podcast'
    | '/yazar-ol'
    | '/admin/login'
    | '/admin/yeni-yazi'
    | '/author/$slug'
    | '/kategori/$slug'
    | '/page/$page'
    | '/admin/'
    | '/admin/duzenle/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AraRoute: typeof AraRoute
  GizlilikPolitikasiRoute: typeof GizlilikPolitikasiRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  SartlarVeKosullarRoute: typeof SartlarVeKosullarRoute
  SeninHayatinNasilDegisirdiRoute: typeof SeninHayatinNasilDegisirdiRoute
  YaPodcastRoute: typeof YaPodcastRoute
  YazarOlRoute: typeof YazarOlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminYeniYaziRoute: typeof AdminYeniYaziRoute
  AuthorSlugRoute: typeof AuthorSlugRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  PagePageRoute: typeof PagePageRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDuzenleIdRoute: typeof AdminDuzenleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ara': {
      id: '/ara'
      path: '/ara'
      fullPath: '/ara'
      preLoaderRoute: typeof AraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik-politikasi': {
      id: '/gizlilik-politikasi'
      path: '/gizlilik-politikasi'
      fullPath: '/gizlilik-politikasi'
      preLoaderRoute: typeof GizlilikPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sartlar-ve-kosullar': {
      id: '/sartlar-ve-kosullar'
      path: '/sartlar-ve-kosullar'
      fullPath: '/sartlar-ve-kosullar'
      preLoaderRoute: typeof SartlarVeKosullarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senin-hayatin-nasil-degisirdi': {
      id: '/senin-hayatin-nasil-degisirdi'
      path: '/senin-hayatin-nasil-degisirdi'
      fullPath: '/senin-hayatin-nasil-degisirdi'
      preLoaderRoute: typeof SeninHayatinNasilDegisirdiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ya-podcast': {
      id: '/ya-podcast'
      path: '/ya-podcast'
      fullPath: '/ya-podcast'
      preLoaderRoute: typeof YaPodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yazar-ol': {
      id: '/yazar-ol'
      path: '/yazar-ol'
      fullPath: '/yazar-ol'
      preLoaderRoute: typeof YazarOlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/yeni-yazi': {
      id: '/admin/yeni-yazi'
      path: '/admin/yeni-yazi'
      fullPath: '/admin/yeni-yazi'
      preLoaderRoute: typeof AdminYeniYaziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$slug': {
      id: '/author/$slug'
      path: '/author/$slug'
      fullPath: '/author/$slug'
      preLoaderRoute: typeof AuthorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$page': {
      id: '/page/$page'
      path: '/page/$page'
      fullPath: '/page/$page'
      preLoaderRoute: typeof PagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/duzenle/$id': {
      id: '/admin/duzenle/$id'
      path: '/admin/duzenle/$id'
      fullPath: '/admin/duzenle/$id'
      preLoaderRoute: typeof AdminDuzenleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AraRoute: AraRoute,
  GizlilikPolitikasiRoute: GizlilikPolitikasiRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  SartlarVeKosullarRoute: SartlarVeKosullarRoute,
  SeninHayatinNasilDegisirdiRoute: SeninHayatinNasilDegisirdiRoute,
  YaPodcastRoute: YaPodcastRoute,
  YazarOlRoute: YazarOlRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminYeniYaziRoute: AdminYeniYaziRoute,
  AuthorSlugRoute: AuthorSlugRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  PagePageRoute: PagePageRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDuzenleIdRoute: AdminDuzenleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
